<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;

/**
 * Generates PROJECT_SNAPSHOT.md — a focused, secret-free inventory of the
 * application (stack, routes, controllers, models + relations, migrations,
 * tables, env var NAMES, mail + payment wiring).
 *
 * Purpose: future coding-agent prompts start from [PROJECT SNAPSHOT] instead
 * of re-reading the whole tree (master plan §33–38). NEVER writes env values,
 * keys or passwords — only variable names and non-secret config flags.
 */
class ProjectSnapshot extends Command
{
    protected $signature = 'dp:snapshot {--out= : Output file (default ../dp-project-plans/PROJECT_SNAPSHOT.md)}';

    protected $description = 'Generate PROJECT_SNAPSHOT.md (secret-free project inventory for AI agents)';

    public function handle()
    {
        $default = base_path('../dp-project-plans/PROJECT_SNAPSHOT.md');
        $out = $this->option('out') ?: $default;
        if (!is_dir(dirname($out))) {
            $out = storage_path('PROJECT_SNAPSHOT.md');
        }

        $md = [];
        $md[] = '# DPLive — PROJECT_SNAPSHOT.md';
        $md[] = '';
        $md[] = '> Auto-generated by `php artisan dp:snapshot`. Secret-free by construction: env values, keys and';
        $md[] = '> passwords are never written — only variable names and non-secret flags.';
        $md[] = '';
        $md[] = '- Generated: ' . now()->toDateTimeString();
        $md[] = '- App env: `' . app()->environment() . '` · App URL: `' . config('app.url') . '`';
        $md[] = '- PHP: ' . PHP_VERSION . ' · Laravel: ' . app()->version();
        $md[] = '- Layout: docroot `C:\laragon\www\dplive` (front controller, css/, js/, uploads/) · app body `deliveringparcel/`';
        $md[] = '';

        // --- 1. Stack ------------------------------------------------------
        $md[] = '## 1. Stack / composer packages';
        $md[] = '';
        $composer = json_decode((string) @file_get_contents(base_path('composer.json')), true);
        foreach (['require', 'require-dev'] as $section) {
            $md[] = '### ' . $section;
            foreach (($composer[$section] ?? []) as $pkg => $constraint) {
                $md[] = '- `' . $pkg . '`: ' . $constraint;
            }
            $md[] = '';
        }
        if (is_file(base_path('package.json'))) {
            $pkg = json_decode((string) @file_get_contents(base_path('package.json')), true);
            $md[] = '### npm (' . count($pkg['dependencies'] ?? []) . ' deps, ' . count($pkg['devDependencies'] ?? []) . ' dev)';
            $md[] = '`' . implode('`, `', array_keys($pkg['dependencies'] ?? [])) . '`';
            $md[] = '';
        }

        // --- 2. Routes -----------------------------------------------------
        $md[] = '## 2. Routes (' . count(Route::getRoutes()) . ')';
        $md[] = '';
        $md[] = '| Methods | URI | Name | Action |';
        $md[] = '|---|---|---|---|';
        foreach (Route::getRoutes() as $route) {
            $md[] = '| ' . implode(',', $route->methods()) . ' | `' . $route->uri() . '` | '
                . ($route->getName() ?: '—') . ' | `' . str_replace('\\', '\\\\', $route->getActionName()) . '` |';
        }
        $md[] = '';

        // --- 3. Flow-focused route subset -----------------------------------
        $md[] = '## 3. Order / offer / payment flow routes (filtered)';
        $md[] = '';
        foreach (Route::getRoutes() as $route) {
            $hay = strtolower($route->uri() . ' ' . $route->getName() . ' ' . $route->getActionName());
            if (preg_match('/order|offer|pay|stripe|bank|chat|freequote|request/', $hay)) {
                $md[] = '- `' . implode(',', $route->methods()) . ' /' . $route->uri() . '` → ' . $route->getActionName()
                    . ($route->getName() ? ' (`' . $route->getName() . '`)' : '');
            }
        }
        $md[] = '';

        // --- 4. Controllers -------------------------------------------------
        $md[] = '## 4. Controllers + public methods';
        $md[] = '';
        foreach ($this->classesIn(app_path('Http/Controllers')) as $class) {
            try {
                $ref = new \ReflectionClass($class);
            } catch (\Throwable $e) {
                continue;
            }
            $methods = [];
            foreach ($ref->getMethods(\ReflectionMethod::IS_PUBLIC) as $m) {
                if ($m->class === $class && !$m->isStatic()) {
                    $methods[] = $m->name . '()';
                }
            }
            if ($methods) {
                $md[] = '- **' . str_replace('App\\Http\\Controllers\\', '', $class) . '**: ' . implode(', ', $methods);
            }
        }
        $md[] = '';

        // --- 5. Models + relations -------------------------------------------
        $md[] = '## 5. Models + relationships';
        $md[] = '';
        $relationCalls = 'hasMany|belongsTo|hasOne|belongsToMany|morphMany|morphTo|hasManyThrough';
        foreach ($this->classesIn(app_path('Models')) as $class) {
            $src = (string) @file_get_contents((new \ReflectionClass($class))->getFileName());
            preg_match_all('/function\s+(\w+)\s*\(\s*\)\s*\{[^}]*\$this->(?:' . $relationCalls . ')\(/', $src, $m);
            $md[] = '- **' . class_basename($class) . '**' . (isset($m[1][0]) ? ' — ' . implode(', ', $m[1]) : '');
        }
        $md[] = '';

        // --- 6. Migrations ----------------------------------------------------
        $md[] = '## 6. Migrations (by year)';
        $md[] = '';
        $files = array_map(fn ($f) => basename($f), glob(base_path('database/migrations/*.php')) ?: []);
        sort($files);
        $byYear = [];
        foreach ($files as $f) {
            $byYear[substr($f, 0, 4)][] = $f;
        }
        foreach ($byYear as $year => $list) {
            $md[] = '### ' . $year . ' (' . count($list) . ')';
            foreach ($list as $f) {
                $md[] = '- ' . $f;
            }
            $md[] = '';
        }

        // --- 7. Live tables ----------------------------------------------------
        $md[] = '## 7. Live database tables';
        $md[] = '';
        $md[] = '| Table | Columns | Rows (approx) |';
        $md[] = '|---|---|---|';
        try {
            $tables = DB::select('SHOW TABLES');
            foreach ($tables as $t) {
                $name = array_values((array) $t)[0];
                try {
                    $cols = count(DB::select('SHOW COLUMNS FROM `' . $name . '`'));
                    $rows = DB::table($name)->count();
                } catch (\Throwable $e) {
                    $cols = '?';
                    $rows = '?';
                }
                $md[] = '| ' . $name . ' | ' . $cols . ' | ' . $rows . ' |';
            }
        } catch (\Throwable $e) {
            $md[] = '_DB unavailable: ' . $e->getMessage() . '_';
        }
        $md[] = '';

        // --- 8. Env var NAMES only ----------------------------------------------
        $md[] = '## 8. .env variable NAMES (values NEVER included)';
        $md[] = '';
        foreach (file(base_path('.env'), FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES) ?: [] as $line) {
            $line = trim($line);
            if ($line === '' || str_starts_with($line, '#')) {
                continue;
            }
            $key = explode('=', $line, 2)[0];
            if ($key !== '') {
                $md[] = '- ' . $key;
            }
        }
        $md[] = '';

        // --- 9. Mail wiring --------------------------------------------------------
        $md[] = '## 9. Mail / notification wiring';
        $md[] = '';
        $md[] = '- MAIL_MAILER: `' . config('mail.default') . '` · from: `' . config('mail.from.address') . '`';
        foreach (glob(app_path('Notifications/*.php')) ?: [] as $f) {
            $src = (string) @file_get_contents($f);
            $envAware = str_contains($src, "app()->environment()") || str_contains($src, 'app()->isEnvironment');
            $md[] = '- Notification `' . basename($f, '.php') . '`: ' . ($envAware ? 'env-aware via()' : 'NOT env-aware');
        }
        $md[] = '- Known local constraint: test users use @dptest.local — real SMTP rejects them (503). Local runs should use `MAIL_MAILER=log`.';
        $md[] = '';

        // --- 10. Payment wiring -----------------------------------------------------
        $md[] = '## 10. Payment engine wiring';
        $md[] = '';
        $md[] = '- Gateways: `' . implode('`, `', array_map('basename', glob(app_path('Services/Payments/*.php')) ?: [])) . '`';
        try {
            foreach (DB::table('payment_methods')->get() as $pm) {
                $md[] = '- payment_methods: `' . $pm->code . '` — ' . $pm->name . ' (' . ($pm->is_enabled ? 'enabled' : 'disabled') . ')';
            }
            foreach (DB::table('payments')->select('status', DB::raw('count(*) n'))->groupBy('status')->get() as $row) {
                $md[] = '- payments by status: ' . $row->status . ' = ' . $row->n;
            }
        } catch (\Throwable $e) {
            $md[] = '- payment tables not readable: ' . $e->getMessage();
        }
        try {
            $engine = \App\Models\Setting::where('key', 'payments_engine_enabled')->value('value');
            $md[] = '- Setting `payments_engine_enabled` = `' . ($engine ?? 'true (default)') . '` (OFF = legacy Stripe-only client tab)';
        } catch (\Throwable $e) {
            // settings table unreadable — skip silently
        }
        $md[] = '- Per-order override column: `orders.forced_payment_method_code` (admin: /admin/orders/{id} → Payment method card)';
        $md[] = '';

        // --- 11. Docs pointers -----------------------------------------------------
        $md[] = '## 11. Planning docs (dp-project-plans/)';
        $md[] = '';
        foreach (array_map('basename', glob(dirname($out) . '/*.md') ?: []) as $f) {
            $md[] = '- ' . $f;
        }
        $md[] = '';

        @file_put_contents($out, implode("\n", $md));
        $this->info('Snapshot written: ' . $out . ' (' . count($md) . ' lines)');
        return 0;
    }

    private function classesIn(string $dir): array
    {
        $classes = [];
        foreach (glob(rtrim($dir, '/\\') . '/*.php') ?: [] as $f) {
            $classes[] = $this->classFromFile($f, app_path());
        }
        foreach (glob(rtrim($dir, '/\\') . '/*', GLOB_ONLYDIR) ?: [] as $sub) {
            foreach ($this->classesIn($sub) as $c) {
                $classes[] = $c;
            }
        }
        return array_values(array_filter($classes));
    }

    private function classFromFile(string $file, string $appPath): ?string
    {
        $rel = str_replace([$appPath, '.php', DIRECTORY_SEPARATOR, '/'], ['', '', '\\', '\\'], $file);
        $rel = ltrim(str_replace('\\\\', '\\', $rel), '\\');
        $class = 'App\\' . ucfirst($rel);
        return class_exists($class) ? $class : null;
    }
}
