<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

if (!class_exists('SeedAllCountries')) {
    class SeedAllCountries extends Migration
    {
        /** ISO 3166-1: name, iso2, iso3, dial code. */
        protected array $countries = [
            ['Andorra', 'AD', 'AND', '376'],
            ['United Arab Emirates', 'AE', 'ARE', '971'],
            ['Afghanistan', 'AF', 'AFG', '93'],
            ['Antigua and Barbuda', 'AG', 'ATG', '1268'],
            ['Anguilla', 'AI', 'AIA', '1264'],
            ['Albania', 'AL', 'ALB', '355'],
            ['Armenia', 'AM', 'ARM', '374'],
            ['Angola', 'AO', 'AGO', '244'],
            ['Antarctica', 'AQ', 'ATA', '672'],
            ['Argentina', 'AR', 'ARG', '54'],
            ['American Samoa', 'AS', 'ASM', '1684'],
            ['Austria', 'AT', 'AUT', '43'],
            ['Australia', 'AU', 'AUS', '61'],
            ['Aruba', 'AW', 'ABW', '297'],
            ['Åland Islands', 'AX', 'ALA', '358'],
            ['Azerbaijan', 'AZ', 'AZE', '994'],
            ['Bosnia and Herzegovina', 'BA', 'BIH', '387'],
            ['Barbados', 'BB', 'BRB', '1246'],
            ['Bangladesh', 'BD', 'BGD', '880'],
            ['Belgium', 'BE', 'BEL', '32'],
            ['Burkina Faso', 'BF', 'BFA', '226'],
            ['Bulgaria', 'BG', 'BGR', '359'],
            ['Bahrain', 'BH', 'BHR', '973'],
            ['Burundi', 'BI', 'BDI', '257'],
            ['Benin', 'BJ', 'BEN', '229'],
            ['Saint Barthélemy', 'BL', 'BLM', '590'],
            ['Bermuda', 'BM', 'BMU', '1441'],
            ['Brunei Darussalam', 'BN', 'BRN', '673'],
            ['Bolivia', 'BO', 'BOL', '591'],
            ['Bonaire, Sint Eustatius and Saba', 'BQ', 'BES', '599'],
            ['Brazil', 'BR', 'BRA', '55'],
            ['Bahamas', 'BS', 'BHS', '1242'],
            ['Bhutan', 'BT', 'BTN', '975'],
            ['Bouvet Island', 'BV', 'BVT', '47'],
            ['Botswana', 'BW', 'BWA', '267'],
            ['Belarus', 'BY', 'BLR', '375'],
            ['Belize', 'BZ', 'BLZ', '501'],
            ['Canada', 'CA', 'CAN', '1'],
            ['Cocos (Keeling) Islands', 'CC', 'CCK', '61'],
            ['Democratic Republic of the Congo', 'CD', 'COD', '243'],
            ['Central African Republic', 'CF', 'CAF', '236'],
            ['Congo', 'CG', 'COG', '242'],
            ['Switzerland', 'CH', 'CHE', '41'],
            ["Côte d'Ivoire", 'CI', 'CIV', '225'],
            ['Cook Islands', 'CK', 'COK', '682'],
            ['Chile', 'CL', 'CHL', '56'],
            ['Cameroon', 'CM', 'CMR', '237'],
            ['China', 'CN', 'CHN', '86'],
            ['Colombia', 'CO', 'COL', '57'],
            ['Costa Rica', 'CR', 'CRI', '506'],
            ['Cuba', 'CU', 'CUB', '53'],
            ['Cabo Verde', 'CV', 'CPV', '238'],
            ['Curaçao', 'CW', 'CUW', '599'],
            ['Christmas Island', 'CX', 'CXR', '61'],
            ['Cyprus', 'CY', 'CYP', '357'],
            ['Czechia', 'CZ', 'CZE', '420'],
            ['Germany', 'DE', 'DEU', '49'],
            ['Djibouti', 'DJ', 'DJI', '253'],
            ['Denmark', 'DK', 'DNK', '45'],
            ['Dominica', 'DM', 'DMA', '1769'],
            ['Dominican Republic', 'DO', 'DOM', '1809'],
            ['Algeria', 'DZ', 'DZA', '213'],
            ['Ecuador', 'EC', 'ECU', '593'],
            ['Estonia', 'EE', 'EST', '372'],
            ['Egypt', 'EG', 'EGY', '20'],
            ['Western Sahara', 'EH', 'ESH', '212'],
            ['Eritrea', 'ER', 'ERI', '291'],
            ['Spain', 'ES', 'ESP', '34'],
            ['Ethiopia', 'ET', 'ETH', '251'],
            ['Finland', 'FI', 'FIN', '358'],
            ['Fiji', 'FJ', 'FJI', '679'],
            ['Falkland Islands', 'FK', 'FLK', '500'],
            ['Micronesia', 'FM', 'FSM', '691'],
            ['Faroe Islands', 'FO', 'FRO', '298'],
            ['France', 'FR', 'FRA', '33'],
            ['Gabon', 'GA', 'GAB', '241'],
            ['United Kingdom', 'GB', 'GBR', '44'],
            ['Grenada', 'GD', 'GRD', '1473'],
            ['Georgia', 'GE', 'GEO', '995'],
            ['French Guiana', 'GF', 'GUF', '594'],
            ['Guernsey', 'GG', 'GGY', '44'],
            ['Ghana', 'GH', 'GHA', '233'],
            ['Gibraltar', 'GI', 'GIB', '350'],
            ['Greenland', 'GL', 'GRL', '299'],
            ['Gambia', 'GM', 'GMB', '220'],
            ['Guinea', 'GN', 'GIN', '224'],
            ['Guadeloupe', 'GP', 'GLP', '590'],
            ['Equatorial Guinea', 'GQ', 'GNQ', '240'],
            ['Greece', 'GR', 'GRC', '30'],
            ['South Georgia and the South Sandwich Islands', 'GS', 'SGS', '500'],
            ['Guatemala', 'GT', 'GTM', '502'],
            ['Guam', 'GU', 'GUM', '1671'],
            ['Guinea-Bissau', 'GW', 'GNB', '245'],
            ['Guyana', 'GY', 'GUY', '592'],
            ['Hong Kong', 'HK', 'HKG', '852'],
            ['Heard Island and McDonald Islands', 'HM', 'HMD', '672'],
            ['Honduras', 'HN', 'HND', '504'],
            ['Croatia', 'HR', 'HRV', '385'],
            ['Haiti', 'HT', 'HTI', '509'],
            ['Hungary', 'HU', 'HUN', '36'],
            ['Indonesia', 'ID', 'IDN', '62'],
            ['Ireland', 'IE', 'IRL', '353'],
            ['Israel', 'IL', 'ISR', '972'],
            ['Isle of Man', 'IM', 'IMN', '44'],
            ['India', 'IN', 'IND', '91'],
            ['British Indian Ocean Territory', 'IO', 'IOT', '246'],
            ['Iraq', 'IQ', 'IRQ', '964'],
            ['Iran', 'IR', 'IRN', '98'],
            ['Iceland', 'IS', 'ISL', '354'],
            ['Italy', 'IT', 'ITA', '39'],
            ['Jersey', 'JE', 'JEY', '44'],
            ['Jamaica', 'JM', 'JAM', '1876'],
            ['Jordan', 'JO', 'JOR', '962'],
            ['Japan', 'JP', 'JPN', '81'],
            ['Kenya', 'KE', 'KEN', '254'],
            ['Kyrgyzstan', 'KG', 'KGZ', '996'],
            ['Cambodia', 'KH', 'KHM', '855'],
            ['Kiribati', 'KI', 'KIR', '686'],
            ['Comoros', 'KM', 'COM', '269'],
            ['Saint Kitts and Nevis', 'KN', 'KNA', '1869'],
            ['North Korea', 'KP', 'PRK', '850'],
            ['South Korea', 'KR', 'KOR', '82'],
            ['Kuwait', 'KW', 'KWT', '965'],
            ['Cayman Islands', 'KY', 'CYM', '1345'],
            ['Kazakhstan', 'KZ', 'KAZ', '7'],
            ['Laos', 'LA', 'LAO', '856'],
            ['Lebanon', 'LB', 'LBN', '961'],
            ['Saint Lucia', 'LC', 'LCA', '1758'],
            ['Liechtenstein', 'LI', 'LIE', '423'],
            ['Sri Lanka', 'LK', 'LKA', '94'],
            ['Liberia', 'LR', 'LBR', '231'],
            ['Lesotho', 'LS', 'LSO', '266'],
            ['Lithuania', 'LT', 'LTU', '370'],
            ['Luxembourg', 'LU', 'LUX', '352'],
            ['Latvia', 'LV', 'LVA', '371'],
            ['Libya', 'LY', 'LBY', '218'],
            ['Morocco', 'MA', 'MAR', '212'],
            ['Monaco', 'MC', 'MCO', '377'],
            ['Moldova', 'MD', 'MDA', '373'],
            ['Montenegro', 'ME', 'MNE', '382'],
            ['Saint Martin', 'MF', 'MAF', '590'],
            ['Madagascar', 'MG', 'MDG', '261'],
            ['Marshall Islands', 'MH', 'MHL', '692'],
            ['North Macedonia', 'MK', 'MKD', '389'],
            ['Mali', 'ML', 'MLI', '223'],
            ['Myanmar', 'MM', 'MMR', '95'],
            ['Mongolia', 'MN', 'MNG', '976'],
            ['Macao', 'MO', 'MAC', '853'],
            ['Northern Mariana Islands', 'MP', 'MNP', '1670'],
            ['Martinique', 'MQ', 'MTQ', '596'],
            ['Mauritania', 'MR', 'MRT', '222'],
            ['Montserrat', 'MS', 'MSR', '1664'],
            ['Malta', 'MT', 'MLT', '356'],
            ['Mauritius', 'MU', 'MUS', '230'],
            ['Maldives', 'MV', 'MDV', '960'],
            ['Malawi', 'MW', 'MWI', '265'],
            ['Mexico', 'MX', 'MEX', '52'],
            ['Malaysia', 'MY', 'MYS', '60'],
            ['Mozambique', 'MZ', 'MOZ', '258'],
            ['Namibia', 'NA', 'NAM', '264'],
            ['New Caledonia', 'NC', 'NCL', '687'],
            ['Niger', 'NE', 'NER', '227'],
            ['Norfolk Island', 'NF', 'NFK', '672'],
            ['Nigeria', 'NG', 'NGA', '234'],
            ['Nicaragua', 'NI', 'NIC', '505'],
            ['Netherlands', 'NL', 'NLD', '31'],
            ['Norway', 'NO', 'NOR', '47'],
            ['Nepal', 'NP', 'NPL', '977'],
            ['Nauru', 'NR', 'NRU', '674'],
            ['Niue', 'NU', 'NIU', '683'],
            ['New Zealand', 'NZ', 'NZL', '64'],
            ['Oman', 'OM', 'OMN', '968'],
            ['Panama', 'PA', 'PAN', '507'],
            ['Peru', 'PE', 'PER', '51'],
            ['French Polynesia', 'PF', 'PYF', '689'],
            ['Papua New Guinea', 'PG', 'PNG', '675'],
            ['Philippines', 'PH', 'PHL', '63'],
            ['Pakistan', 'PK', 'PAK', '92'],
            ['Poland', 'PL', 'POL', '48'],
            ['Saint Pierre and Miquelon', 'PM', 'SPM', '508'],
            ['Pitcairn', 'PN', 'PCN', '870'],
            ['Puerto Rico', 'PR', 'PRI', '1787'],
            ['Palestine', 'PS', 'PSE', '970'],
            ['Portugal', 'PT', 'PRT', '351'],
            ['Palau', 'PW', 'PLW', '680'],
            ['Paraguay', 'PY', 'PRY', '595'],
            ['Qatar', 'QA', 'QAT', '974'],
            ['Réunion', 'RE', 'REU', '262'],
            ['Romania', 'RO', 'ROU', '40'],
            ['Serbia', 'RS', 'SRB', '381'],
            ['Russia', 'RU', 'RUS', '7'],
            ['Rwanda', 'RW', 'RWA', '250'],
            ['Saudi Arabia', 'SA', 'SAU', '966'],
            ['Solomon Islands', 'SB', 'SLB', '677'],
            ['Seychelles', 'SC', 'SYC', '248'],
            ['Sudan', 'SD', 'SDN', '249'],
            ['Sweden', 'SE', 'SWE', '46'],
            ['Singapore', 'SG', 'SGP', '65'],
            ['Saint Helena', 'SH', 'SHN', '290'],
            ['Slovenia', 'SI', 'SVN', '386'],
            ['Svalbard and Jan Mayen', 'SJ', 'SJM', '47'],
            ['Slovakia', 'SK', 'SVK', '421'],
            ['Sierra Leone', 'SL', 'SLE', '232'],
            ['San Marino', 'SM', 'SMR', '378'],
            ['Senegal', 'SN', 'SEN', '221'],
            ['Somalia', 'SO', 'SOM', '252'],
            ['Suriname', 'SR', 'SUR', '597'],
            ['South Sudan', 'SS', 'SSD', '211'],
            ['Sao Tome and Principe', 'ST', 'STP', '239'],
            ['El Salvador', 'SV', 'SLV', '503'],
            ['Sint Maarten', 'SX', 'SXM', '1721'],
            ['Syrian Arab Republic', 'SY', 'SYR', '963'],
            ['Eswatini', 'SZ', 'SWZ', '268'],
            ['Turks and Caicos Islands', 'TC', 'TCA', '1649'],
            ['Chad', 'TD', 'TCD', '235'],
            ['French Southern Territories', 'TF', 'ATF', '262'],
            ['Togo', 'TG', 'TGO', '228'],
            ['Thailand', 'TH', 'THA', '66'],
            ['Tajikistan', 'TJ', 'TJK', '992'],
            ['Tokelau', 'TK', 'TKL', '690'],
            ['Timor-Leste', 'TL', 'TLS', '670'],
            ['Turkmenistan', 'TM', 'TKM', '993'],
            ['Tunisia', 'TN', 'TUN', '216'],
            ['Tonga', 'TO', 'TON', '676'],
            ['Turkey', 'TR', 'TUR', '90'],
            ['Trinidad and Tobago', 'TT', 'TTO', '1868'],
            ['Tuvalu', 'TV', 'TUV', '688'],
            ['Taiwan', 'TW', 'TWN', '886'],
            ['Tanzania', 'TZ', 'TZA', '255'],
            ['Ukraine', 'UA', 'UKR', '380'],
            ['Uganda', 'UG', 'UGA', '256'],
            ['United States Minor Outlying Islands', 'UM', 'UMI', '1'],
            ['United States', 'US', 'USA', '1'],
            ['Uruguay', 'UY', 'URY', '598'],
            ['Uzbekistan', 'UZ', 'UZB', '998'],
            ['Holy See (Vatican City)', 'VA', 'VAT', '39'],
            ['Saint Vincent and the Grenadines', 'VC', 'VCT', '1784'],
            ['Venezuela', 'VE', 'VEN', '58'],
            ['Virgin Islands (British)', 'VG', 'VGB', '1284'],
            ['Virgin Islands (U.S.)', 'VI', 'VIR', '1340'],
            ['Vietnam', 'VN', 'VNM', '84'],
            ['Vanuatu', 'VU', 'VUT', '678'],
            ['Wallis and Futuna', 'WF', 'WLF', '681'],
            ['Samoa', 'WS', 'WSM', '685'],
            ['Yemen', 'YE', 'YEM', '967'],
            ['Mayotte', 'YT', 'MYT', '262'],
            ['South Africa', 'ZA', 'ZAF', '27'],
            ['Zambia', 'ZM', 'ZMB', '260'],
            ['Zimbabwe', 'ZW', 'ZWE', '263'],
        ];

        public function up()
        {
            if (!Schema::hasTable('countries')) {
                return;
            }

            $now = now();
            foreach ($this->countries as [$name, $iso2, $iso3, $dial]) {
                $exists = DB::table('countries')->where('iso2', $iso2)->exists();
                if ($exists) {
                    continue; // never touch admin-configured rows
                }
                DB::table('countries')->insert([
                    'name'               => $name,
                    'iso2'               => $iso2,
                    'iso3'               => $iso3,
                    'dial_code'          => $dial,
                    'is_active'          => 0,
                    'shipping_rate'      => null,
                    'allow_request_from' => 0,
                    'allow_delivery_to'  => 0,
                    'allow_shipper'      => 0,
                    'created_at'         => $now,
                    'updated_at'         => $now,
                ]);
            }
        }

        public function down()
        {
            // Only remove rows this migration added (disabled, no rate).
            $isos = array_column($this->countries, 1);
            DB::table('countries')
                ->whereIn('iso2', $isos)
                ->where('is_active', 0)
                ->whereNull('shipping_rate')
                ->where('allow_request_from', 0)
                ->where('allow_delivery_to', 0)
                ->where('allow_shipper', 0)
                ->delete();
        }
    }
}
